services:
  app:
    build: .
    container_name: curso-deploy-app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/var/www
    depends_on:
      db:
        condition: service_healthy

  queue:
    build: ./.docker/queue
    container_name: curso-deploy-queue
    volumes:
      - .:/var/www
    depends_on:
      - app
      - redis

  nginx:
    build: .docker/nginx
    container_name: curso-deploy-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: curso-deploy-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 3

  phpmyadmin:
    depends_on:
      - db
    container_name: curso-deploy-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MEMORY_LIMIT=1024M
      - UPLOAD_LIMIT=12200M

  redis:
    image: redis:alpine
    container_name: curso-deploy-redis
    expose:
      - 6379

volumes:
  dbdata:
    driver: local
